"""
AlphaFold DB - Auto-generated Router
====================================
Generated by: Autonomous API Discovery Agent
Generated at: 2026-04-16T03:05:28.046912
Source: https://alphafold.ebi.ac.uk/
Category: structure
Description: AI-predicted 3D protein structures

Endpoints:
  - GET /prediction/{uniprot_id}: Get AlphaFold prediction
  - GET /entry/{uniprot_id}: Get entry metadata

Usage:
    from apis.AlphaFold import alphafold_router
    app.include_router(alphafold_router)
"""
from fastapi import APIRouter, HTTPException
from typing import Dict, Any
import requests
import logging

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/alphafold", tags=["AlphaFold DB"])

api_info = {
    "name": "AlphaFold DB",
    "base_url": "https://alphafold.ebi.ac.uk/api",
    "prefix": "/alphafold",
    "category": "structure",
    "description": "AI-predicted 3D protein structures",
    "source": "https://alphafold.ebi.ac.uk/"
}


@router.get("/prediction/{uniprot_id}")
async def prediction_uniprot_id(uniprot_id: str, ):
    """Get AlphaFold prediction"""
    try:
        url = f"{api_info['base_url']}/prediction/{uniprot_id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "AlphaFold DB", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/entry/{uniprot_id}")
async def entry_uniprot_id(uniprot_id: str, ):
    """Get entry metadata"""
    try:
        url = f"{api_info['base_url']}/entry/{uniprot_id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "AlphaFold DB", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all endpoints for this API"""
    return {
        "api": "AlphaFold DB",
        "base_url": "https://alphafold.ebi.ac.uk/api",
        "category": "structure",
        "endpoints": [{'path': '/prediction/{uniprot_id}', 'method': 'GET', 'description': 'Get AlphaFold prediction'}, {'path': '/entry/{uniprot_id}', 'method': 'GET', 'description': 'Get entry metadata'}]
    }
