"""
Reactome - Auto-generated Router
====================================
Generated by: Autonomous API Discovery Agent
Generated at: 2026-04-16T02:56:47.417584
Source: https://reactome.org/dev
Category: pathway-analysis
Description: Free, open-source, curated and peer-reviewed pathway database

Endpoints:
  - GET /data/pathways/low/entity/{id}: Get pathways for a given entity
  - GET /data/query/enhanced/{id}: Get enhanced details for an entity
  - GET /data/species/all: List all species in Reactome

Usage:
    from apis.Reactome import reactome_router
    app.include_router(reactome_router)
"""
from fastapi import APIRouter, HTTPException
from typing import Dict, Any
import requests
import logging

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/reactome", tags=["Reactome"])

api_info = {
    "name": "Reactome",
    "base_url": "https://reactome.org/ContentService",
    "prefix": "/reactome",
    "category": "pathway-analysis",
    "description": "Free, open-source, curated and peer-reviewed pathway database",
    "source": "https://reactome.org/dev"
}


@router.get("/data/pathways/low/entity/{id}")
async def data_pathways_low_entity_id(id: str, ):
    """Get pathways for a given entity"""
    try:
        url = f"{api_info['base_url']}/data/pathways/low/entity/{id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "Reactome", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/data/query/enhanced/{id}")
async def data_query_enhanced_id(id: str, ):
    """Get enhanced details for an entity"""
    try:
        url = f"{api_info['base_url']}/data/query/enhanced/{id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "Reactome", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/data/species/all")
async def data_species_all():
    """List all species in Reactome"""
    try:
        url = f"{api_info['base_url']}/data/species/all"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "Reactome", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all endpoints for this API"""
    return {
        "api": "Reactome",
        "base_url": "https://reactome.org/ContentService",
        "category": "pathway-analysis",
        "endpoints": [{'path': '/data/pathways/low/entity/{id}', 'method': 'GET', 'description': 'Get pathways for a given entity'}, {'path': '/data/query/enhanced/{id}', 'method': 'GET', 'description': 'Get enhanced details for an entity'}, {'path': '/data/species/all', 'method': 'GET', 'description': 'List all species in Reactome'}]
    }
