"""
Clustal Omega - Auto-generated Router
====================================
Generated by: Autonomous API Discovery Agent
Generated at: 2026-04-16T02:53:08.820986
Source: https://www.ebi.ac.uk/Tools/msa/clustalo/
Category: alignment
Description: Multiple sequence alignment from EBI

Endpoints:
  - POST /job: Submit alignment job
  - GET /status/{job_id}: Check job status
  - GET /result/{job_id}: Get alignment results
  - GET /parameters: Get available parameters

Usage:
    from apis.Clustalo import clustalo_router
    app.include_router(clustalo_router)
"""
from fastapi import APIRouter, HTTPException
from typing import Dict, Any
import requests
import logging

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/clustalo", tags=["Clustal Omega"])

api_info = {
    "name": "Clustal Omega",
    "base_url": "https://www.ebi.ac.uk/Tools/services/rest/clustalo",
    "prefix": "/clustalo",
    "category": "alignment",
    "description": "Multiple sequence alignment from EBI",
    "source": "https://www.ebi.ac.uk/Tools/msa/clustalo/"
}


@router.post("/job")
async def job(data: Dict[str, Any] = None):
    """Submit alignment job"""
    try:
        url = f"{api_info['base_url']}/job"
        r = requests.post(url, json=data or {}, timeout=60)
        r.raise_for_status()
        return {"status": "success", "api": "Clustal Omega", "data": r.json() if r.text else {"ok": True}}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/status/{job_id}")
async def status_job_id(job_id: str, ):
    """Check job status"""
    try:
        url = f"{api_info['base_url']}/status/{job_id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "Clustal Omega", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/result/{job_id}")
async def result_job_id(job_id: str, ):
    """Get alignment results"""
    try:
        url = f"{api_info['base_url']}/result/{job_id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "Clustal Omega", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/parameters")
async def parameters():
    """Get available parameters"""
    try:
        url = f"{api_info['base_url']}/parameters"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "Clustal Omega", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all endpoints for this API"""
    return {
        "api": "Clustal Omega",
        "base_url": "https://www.ebi.ac.uk/Tools/services/rest/clustalo",
        "category": "alignment",
        "endpoints": [{'path': '/job', 'method': 'POST', 'description': 'Submit alignment job'}, {'path': '/status/{job_id}', 'method': 'GET', 'description': 'Check job status'}, {'path': '/result/{job_id}', 'method': 'GET', 'description': 'Get alignment results'}, {'path': '/parameters', 'method': 'GET', 'description': 'Get available parameters'}]
    }
