# Auto-generated router for Clustal Omega
# Generated by autonomous agent at 2026-04-12T03:37:51.347539
# Source: EBI Tools
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Dict, Any, List
import requests
import logging

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/clustal_omega", tags=["Clustal Omega"])

# API Configuration
api_info = {
    "name": "Clustal Omega",
    "base_url": "https://www.ebi.ac.uk/Tools/services/rest/clustalo",
    "prefix": "/clustal_omega",
    "category": "alignment",
    "description": "Multiple sequence alignment",
    "source": "EBI Tools"
}


@router.post("/job")
async def job(data: Dict[str, Any] = None):
    """Submit alignment job"""
    try:
        url = f"{api_info['base_url']}/job"
        data = data or {}
        response = requests.post(url, data=data, timeout=60)
        response.raise_for_status()
        return {
            "status": "success",
            "api_name": "Clustal Omega",
            "data": response.json() if response.text else {"message": "Request successful"}
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"job failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/status/{job_id}")
async def status_job_id(job_id: str):
    """Check job status"""
    try:
        url = f"{api_info['base_url']}/status/{job_id}"
        response = requests.get(url, timeout=30)
        response.raise_for_status()
        return {
            "status": "success",
            "api_name": "Clustal Omega",
            "data": response.json()
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"status_job_id failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/result/{job_id}")
async def result_job_id(job_id: str):
    """Get alignment results"""
    try:
        url = f"{api_info['base_url']}/result/{job_id}"
        response = requests.get(url, timeout=30)
        response.raise_for_status()
        return {
            "status": "success",
            "api_name": "Clustal Omega",
            "data": response.json()
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"result_job_id failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all available endpoints for this API"""
    return {
        "api_name": "Clustal Omega",
        "base_url": "https://www.ebi.ac.uk/Tools/services/rest/clustalo",
        "category": "alignment",
        "description": "Multiple sequence alignment",
        "endpoints": [
            {"path": "/job", "method": "POST", "description": "Submit alignment job"},
            {"path": "/status/{job_id}", "method": "GET", "description": "Check job status"},
            {"path": "/result/{job_id}", "method": "GET", "description": "Get alignment results"}
        ]
    }
