# Auto-generated router for Ensembl Genomics API
# Generated by autonomous agent at 2026-04-12T03:53:11.848861
# Source: Ensembl REST API
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Dict, Any, List
import requests
import logging

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/ensembl_genomics", tags=["Ensembl Genomics API"])

# API Configuration
api_info = {
    "name": "Ensembl Genomics API",
    "base_url": "https://rest.ensembl.org",
    "prefix": "/ensembl_genomics",
    "category": "genomics",
    "description": "Ensembl genomics endpoints",
    "source": "Ensembl REST API"
}


@router.get("/overlap/region/{species}/{region}")
async def overlap_region_species_region(species: str, region: str):
    """Get features in a genomic region"""
    try:
        url = f"{api_info['base_url']}/overlap/region/{species}/{region}"
        response = requests.get(url, timeout=30)
        response.raise_for_status()
        return {
            "status": "success",
            "api_name": "Ensembl Genomics API",
            "data": response.json()
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"overlap_region_species_region failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all available endpoints for this API"""
    return {
        "api_name": "Ensembl Genomics API",
        "base_url": "https://rest.ensembl.org",
        "category": "genomics",
        "description": "Ensembl genomics endpoints",
        "endpoints": [
            {"path": "/overlap/region/{species}/{region}", "method": "GET", "description": "Get features in a genomic region"}
        ]
    }
