"""
Ensembl - Auto-generated Router
====================================
Generated by: Autonomous API Discovery Agent
Generated at: 2026-04-16T02:56:40.912717
Source: https://rest.ensembl.org
Category: genomics
Description: Genomic data, annotation, and variation from Ensembl

Endpoints:
  - GET /lookup/symbol/{species}/{symbol}: Look up an Ensembl ID by symbol
  - GET /sequence/id/{id}: Request a sequence by its stable ID
  - GET /variation/{species}/{id}: Get variation data by ID
  - GET /xrefs/id/{id}: Get external references for an Ensembl ID

Usage:
    from apis.Ensembl import ensembl_router
    app.include_router(ensembl_router)
"""
from fastapi import APIRouter, HTTPException
from typing import Dict, Any
import requests
import logging

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/ensembl", tags=["Ensembl"])

api_info = {
    "name": "Ensembl",
    "base_url": "https://rest.ensembl.org",
    "prefix": "/ensembl",
    "category": "genomics",
    "description": "Genomic data, annotation, and variation from Ensembl",
    "source": "https://rest.ensembl.org"
}


@router.get("/lookup/symbol/{species}/{symbol}")
async def lookup_symbol_species_symbol(species: str, symbol: str, ):
    """Look up an Ensembl ID by symbol"""
    try:
        url = f"{api_info['base_url']}/lookup/symbol/{species}/{symbol}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "Ensembl", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/sequence/id/{id}")
async def sequence_id_id(id: str, ):
    """Request a sequence by its stable ID"""
    try:
        url = f"{api_info['base_url']}/sequence/id/{id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "Ensembl", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/variation/{species}/{id}")
async def variation_species_id(species: str, id: str, ):
    """Get variation data by ID"""
    try:
        url = f"{api_info['base_url']}/variation/{species}/{id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "Ensembl", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/xrefs/id/{id}")
async def xrefs_id_id(id: str, ):
    """Get external references for an Ensembl ID"""
    try:
        url = f"{api_info['base_url']}/xrefs/id/{id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "Ensembl", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all endpoints for this API"""
    return {
        "api": "Ensembl",
        "base_url": "https://rest.ensembl.org",
        "category": "genomics",
        "endpoints": [{'path': '/lookup/symbol/{species}/{symbol}', 'method': 'GET', 'description': 'Look up an Ensembl ID by symbol'}, {'path': '/sequence/id/{id}', 'method': 'GET', 'description': 'Request a sequence by its stable ID'}, {'path': '/variation/{species}/{id}', 'method': 'GET', 'description': 'Get variation data by ID'}, {'path': '/xrefs/id/{id}', 'method': 'GET', 'description': 'Get external references for an Ensembl ID'}]
    }
