# Auto-generated router for Ensembl Sequence API
# Generated by autonomous agent at 2026-04-12T03:53:11.845843
# Source: Ensembl REST API
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Dict, Any, List
import requests
import logging

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/ensembl_sequence", tags=["Ensembl Sequence API"])

# API Configuration
api_info = {
    "name": "Ensembl Sequence API",
    "base_url": "https://rest.ensembl.org",
    "prefix": "/ensembl_sequence",
    "category": "sequence",
    "description": "Ensembl sequence endpoints",
    "source": "Ensembl REST API"
}


@router.get("/sequence/id/{id}")
async def sequence_id_id(id: str):
    """Fetch sequence by stable ID"""
    try:
        url = f"{api_info['base_url']}/sequence/id/{id}"
        response = requests.get(url, timeout=30)
        response.raise_for_status()
        return {
            "status": "success",
            "api_name": "Ensembl Sequence API",
            "data": response.json()
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"sequence_id_id failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all available endpoints for this API"""
    return {
        "api_name": "Ensembl Sequence API",
        "base_url": "https://rest.ensembl.org",
        "category": "sequence",
        "description": "Ensembl sequence endpoints",
        "endpoints": [
            {"path": "/sequence/id/{id}", "method": "GET", "description": "Fetch sequence by stable ID"}
        ]
    }
