# Auto-generated router for Ensembl Info API
# Generated by autonomous agent at 2026-04-12T03:53:11.848066
# Source: Ensembl REST API
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Dict, Any, List
import requests
import logging

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/ensembl_info", tags=["Ensembl Info API"])

# API Configuration
api_info = {
    "name": "Ensembl Info API",
    "base_url": "https://rest.ensembl.org",
    "prefix": "/ensembl_info",
    "category": "info",
    "description": "Ensembl info endpoints",
    "source": "Ensembl REST API"
}


@router.get("/info/species")
async def info_species():
    """List all species in Ensembl"""
    try:
        url = f"{api_info['base_url']}/info/species"
        response = requests.get(url, timeout=30)
        response.raise_for_status()
        return {
            "status": "success",
            "api_name": "Ensembl Info API",
            "data": response.json()
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"info_species failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/info/ping")
async def info_ping():
    """Check if Ensembl REST is alive"""
    try:
        url = f"{api_info['base_url']}/info/ping"
        response = requests.get(url, timeout=30)
        response.raise_for_status()
        return {
            "status": "success",
            "api_name": "Ensembl Info API",
            "data": response.json()
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"info_ping failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all available endpoints for this API"""
    return {
        "api_name": "Ensembl Info API",
        "base_url": "https://rest.ensembl.org",
        "category": "info",
        "description": "Ensembl info endpoints",
        "endpoints": [
            {"path": "/info/species", "method": "GET", "description": "List all species in Ensembl"},
            {"path": "/info/ping", "method": "GET", "description": "Check if Ensembl REST is alive"}
        ]
    }
