"""
T-Coffee - Auto-generated Router
====================================
Generated by: Autonomous API Discovery Agent
Generated at: 2026-04-16T02:53:11.912151
Source: https://www.ebi.ac.uk/Tools/msa/tcoffee/
Category: alignment
Description: Consistency-based multiple sequence alignment

Endpoints:
  - POST /job: Submit T-Coffee alignment
  - GET /status/{job_id}: Check alignment status
  - GET /result/{job_id}: Get alignment result

Usage:
    from apis.TCoffee import tcoffee_router
    app.include_router(tcoffee_router)
"""
from fastapi import APIRouter, HTTPException
from typing import Dict, Any
import requests
import logging

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/tcoffee", tags=["T-Coffee"])

api_info = {
    "name": "T-Coffee",
    "base_url": "https://www.ebi.ac.uk/Tools/services/rest/tcoffee",
    "prefix": "/tcoffee",
    "category": "alignment",
    "description": "Consistency-based multiple sequence alignment",
    "source": "https://www.ebi.ac.uk/Tools/msa/tcoffee/"
}


@router.post("/job")
async def job(data: Dict[str, Any] = None):
    """Submit T-Coffee alignment"""
    try:
        url = f"{api_info['base_url']}/job"
        r = requests.post(url, json=data or {}, timeout=60)
        r.raise_for_status()
        return {"status": "success", "api": "T-Coffee", "data": r.json() if r.text else {"ok": True}}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/status/{job_id}")
async def status_job_id(job_id: str, ):
    """Check alignment status"""
    try:
        url = f"{api_info['base_url']}/status/{job_id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "T-Coffee", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/result/{job_id}")
async def result_job_id(job_id: str, ):
    """Get alignment result"""
    try:
        url = f"{api_info['base_url']}/result/{job_id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "T-Coffee", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all endpoints for this API"""
    return {
        "api": "T-Coffee",
        "base_url": "https://www.ebi.ac.uk/Tools/services/rest/tcoffee",
        "category": "alignment",
        "endpoints": [{'path': '/job', 'method': 'POST', 'description': 'Submit T-Coffee alignment'}, {'path': '/status/{job_id}', 'method': 'GET', 'description': 'Check alignment status'}, {'path': '/result/{job_id}', 'method': 'GET', 'description': 'Get alignment result'}]
    }
