// Auto-generated API index - ALL 21 Discovered Bioinformatics Services
// Generated by autonomous agent - Updated 2026-04-16

// Alignment/Structure APIs
import { ClustalOmegaClient } from './clustal_omega.ts';
import { TCoffeeClient } from './t_coffee.ts';
import { MAFFTClient } from './mafft.ts';
import { MuscleClient } from './muscle.ts';
import { JalviewClient } from './jalview.ts';
import { AlphaFoldClient } from './alphafold.ts';
import { PDBEClient } from './pdbe.ts';
import { SwissModelClient } from './swissmodel.ts';

// Search/Query APIs
import { BLASTClient } from './blast.ts';
import { NCBIClient } from './ncbi.ts';
import { HMMERClient } from './hmmer.ts';
import { EnsemblSequenceAPIClient } from './ensembl_sequence.ts';
import { EnsemblSearchAPIClient } from './ensembl_search.ts';

// Genomics/Data APIs
import { EnsemblInfoAPIClient } from './ensembl_info.ts';
import { EnsemblGenomicsAPIClient } from './ensembl_genomics.ts';
import { EnsemblEvolutionAPIClient } from './ensembl_evolution.ts';
import { UniProtAPIClient } from './search/uniprot.ts';

// Annotation/Analysis APIs
import { InterProClient } from './interpro.ts';
import { GeneOntologyClient } from './geneontology.ts';
import { ReactomeClient } from './reactome.ts';

// Variant Prediction API
import { SIFTClient } from './sift.ts';

export {
  // Alignment/Structure
  ClustalOmegaClient,
  TCoffeeClient,
  MAFFTClient,
  MuscleClient,
  JalviewClient,
  AlphaFoldClient,
  PDBEClient,
  SwissModelClient,
  // Search/Query
  BLASTClient,
  NCBIClient,
  HMMERClient,
  EnsemblSequenceAPIClient,
  EnsemblSearchAPIClient,
  // Genomics/Data
  EnsemblInfoAPIClient,
  EnsemblGenomicsAPIClient,
  EnsemblEvolutionAPIClient,
  UniProtAPIClient,
  // Annotation/Analysis
  InterProClient,
  GeneOntologyClient,
  ReactomeClient,
  // Variant Prediction
  SIFTClient
};

export interface APIRegistry {
  name: string;
  category: string;
  subcategory: string;
  client: any;
  description: string;
  requiresSequence: boolean;
  supportsJobQueue: boolean;
}

export const ALL_APIS: APIRegistry[] = [
  // ALIGNMENT TOOLS (5)
  { name: 'Clustal Omega', category: 'alignment', subcategory: 'pairwise', client: ClustalOmegaClient, description: 'Rapid multiple sequence alignment', requiresSequence: true, supportsJobQueue: true },
  { name: 'T-Coffee', category: 'alignment', subcategory: 'multiple', client: TCoffeeClient, description: 'Combined phylogenetic and structural alignment', requiresSequence: true, supportsJobQueue: true },
  { name: 'MAFFT', category: 'alignment', subcategory: 'multiple', client: MAFFTClient, description: 'Fast multiple sequence alignment', requiresSequence: true, supportsJobQueue: true },
  { name: 'MUSCLE', category: 'alignment', subcategory: 'multiple', client: MuscleClient, description: 'Multiple sequence comparison by log-expectation', requiresSequence: true, supportsJobQueue: true },
  { name: 'Jalview', category: 'alignment', subcategory: 'visualization', client: JalviewClient, description: 'Visualize and edit alignments', requiresSequence: false, supportsJobQueue: false },

  // STRUCTURE PREDICTION (3)
  { name: 'AlphaFold DB', category: 'structure', subcategory: 'prediction', client: AlphaFoldClient, description: 'AI-based protein structure prediction', requiresSequence: true, supportsJobQueue: true },
  { name: 'SWISS-MODEL', category: 'structure', subcategory: 'prediction', client: SwissModelClient, description: 'Automated protein structure homology modelling', requiresSequence: true, supportsJobQueue: true },
  { name: 'PDBe', category: 'structure', subcategory: 'database', client: PDBEClient, description: 'Protein Data Bank in Europe - search 3D structures', requiresSequence: false, supportsJobQueue: false },

  // SEQUENCE SEARCH (5)
  { name: 'NCBI BLAST', category: 'search', subcategory: 'sequence', client: BLASTClient, description: 'Basic Local Alignment Search Tool', requiresSequence: true, supportsJobQueue: true },
  { name: 'NCBI E-utilities', category: 'search', subcategory: 'database', client: NCBIClient, description: 'NCBI database search and retrieval', requiresSequence: false, supportsJobQueue: false },
  { name: 'HMMER', category: 'search', subcategory: 'hmm', client: HMMERClient, description: 'Hidden Markov Model-based sequence searching', requiresSequence: true, supportsJobQueue: true },
  { name: 'Ensembl Sequence', category: 'search', subcategory: 'genomics', client: EnsemblSequenceAPIClient, description: 'Query genomic sequences', requiresSequence: true, supportsJobQueue: false },
  { name: 'Ensembl Search', category: 'search', subcategory: 'genomics', client: EnsemblSearchAPIClient, description: 'Search Ensembl database', requiresSequence: false, supportsJobQueue: false },

  // GENOMICS/DATA (4)
  { name: 'Ensembl Info', category: 'genomics', subcategory: 'info', client: EnsemblInfoAPIClient, description: 'Genomic information and metadata', requiresSequence: false, supportsJobQueue: false },
  { name: 'Ensembl Genomics', category: 'genomics', subcategory: 'analysis', client: EnsemblGenomicsAPIClient, description: 'Genomic analysis and statistics', requiresSequence: false, supportsJobQueue: false },
  { name: 'Ensembl Evolution', category: 'genomics', subcategory: 'evolution', client: EnsemblEvolutionAPIClient, description: 'Evolutionary comparative genomics', requiresSequence: false, supportsJobQueue: false },
  { name: 'UniProt', category: 'genomics', subcategory: 'protein', client: UniProtAPIClient, description: 'Universal Protein Resource - protein sequences and annotations', requiresSequence: true, supportsJobQueue: false },

  // ANNOTATION (3)
  { name: 'InterPro', category: 'annotation', subcategory: 'domains', client: InterProClient, description: 'Protein families, domains and functional sites', requiresSequence: true, supportsJobQueue: false },
  { name: 'Gene Ontology', category: 'annotation', subcategory: 'ontology', client: GeneOntologyClient, description: 'Gene Ontology annotations and terms', requiresSequence: false, supportsJobQueue: false },
  { name: 'Reactome', category: 'annotation', subcategory: 'pathway', client: ReactomeClient, description: 'Pathway database for protein reactions', requiresSequence: false, supportsJobQueue: false },

  // VARIANT PREDICTION (1)
  { name: 'SIFT', category: 'variant', subcategory: 'effect', client: SIFTClient, description: 'Sorting Intolerant From Tolerant - variant effect prediction', requiresSequence: true, supportsJobQueue: true },
];

export async function discoverAllAPIs(): Promise<any[]> {
  const discoveries = await Promise.allSettled(
    ALL_APIS.map(api => api.client.discover().catch(err => ({ error: err.message })))
  );
  return discoveries.map((result, idx) => ({
    api: ALL_APIS[idx].name,
    status: result.status === 'fulfilled' ? 'success' : 'failed',
    data: result.status === 'fulfilled' ? result.value : result.reason
  }));
}

export function getAPIsByCategory(category: string): APIRegistry[] {
  return ALL_APIS.filter(api => api.category === category);
}

export function getAllAPIs(): APIRegistry[] {
  return ALL_APIS;
}

export function getAPIByName(name: string): APIRegistry | undefined {
  return ALL_APIS.find(api => api.name === name);
}
