// Auto-generated API client for Ensembl Genomics API
// Generated by autonomous agent at 2026-04-12T03:22:31.131200
// Source: Ensembl REST API

const API_CONFIG = {
  BACKEND_URL: import.meta.env.VITE_BACKEND_URL || 'http://localhost:8000'
};

export class EnsemblGenomicsAPIClient {
  static readonly API_NAME = "Ensembl Genomics API";
  static readonly BASE_URL = "https://rest.ensembl.org";
  static readonly PREFIX = "/ensembl_genomics";


  static async overlap_region_species_region(params?: { [key: string]: string }): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/ensembl_genomics/overlap/region/{species}/{region}`;
    const queryString = params ? '?' + new URLSearchParams(params).toString() : '';
    const response = await fetch(url + queryString);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return response.json();
  }

  static async discover(): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/ensembl_genomics/discover`;
    const response = await fetch(url);
    if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);
    return response.json();
  }
}
