// Auto-generated API client for Ensembl Evolution API
// Generated by autonomous agent at 2026-04-12T03:17:23.168153
// Source: Ensembl REST API

const API_CONFIG = {
  BACKEND_URL: import.meta.env.VITE_BACKEND_URL || 'http://localhost:8000'
};

export class EnsemblEvolutionAPIClient {
  static readonly API_NAME = "Ensembl Evolution API";
  static readonly BASE_URL = "https://rest.ensembl.org";
  static readonly PREFIX = "/ensembl_evolution";


  static async homology_id_id(params?: { [key: string]: string }): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/ensembl_evolution/homology/id/{id}`;
    const queryString = params ? '?' + new URLSearchParams(params).toString() : '';
    const response = await fetch(url + queryString);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return response.json();
  }

  static async discover(): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/ensembl_evolution/discover`;
    const response = await fetch(url);
    if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);
    return response.json();
  }
}
