// Auto-generated API client for UniProt Integration API
// Generated by autonomous agent

const API_CONFIG = {
  BACKEND_URL: import.meta.env.VITE_BACKEND_URL || 'http://localhost:8000'
};

export class UniProtAPIClient {
  static readonly API_NAME = "UniProt Integration API";
  static readonly BASE_URL = "https://rest.uniprot.org";
  static readonly PREFIX = "/uniprot";

  static async health(): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/uniprot/health`;
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return response.json();
  }

  static async search(data: { query: string; size?: number; offset?: number }): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/uniprot/search`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    });
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return response.json();
  }

  static async accession(accession: string): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/uniprot/accession/${accession}`;
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return response.json();
  }

  static async idmapping(data: { ids: string[]; from_db?: string; to_db?: string }): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/uniprot/idmapping`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    });
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return response.json();
  }

  static async validateSequences(data: { sequences: string[] }): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/uniprot/validate-sequences`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    });
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return response.json();
  }

  static async resolveMismatches(data: { 
    frontend_sequences: string[]; 
    backend_sequences: string[]; 
    resolution_strategy?: string 
  }): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/uniprot/resolve-mismatches`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    });
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return response.json();
  }

  static async fetchAndAnalyze(data: { accessions: string[] }): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/uniprot/fetch-and-analyze`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    });
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return response.json();
  }

  static async discover(): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/uniprot/discover`;
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return response.json();
  }
}
