"""
Gene Ontology - Auto-generated Router
====================================
Generated by: Autonomous API Discovery Agent
Generated at: 2026-04-16T03:05:30.903466
Source: http://geneontology.org/
Category: annotation
Description: The Gene Ontology resource for gene function information

Endpoints:
  - GET /bioentity/gene/{id}: Get GO annotations for a gene
  - GET /ontology/term/{id}: Get details for a GO term
  - GET /search/entity/autocomplete/{term}: Autocomplete search for entities

Usage:
    from apis.GeneOntology import geneontology_router
    app.include_router(geneontology_router)
"""
from fastapi import APIRouter, HTTPException
from typing import Dict, Any
import requests
import logging

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/go", tags=["Gene Ontology"])

api_info = {
    "name": "Gene Ontology",
    "base_url": "http://api.geneontology.org/api",
    "prefix": "/go",
    "category": "annotation",
    "description": "The Gene Ontology resource for gene function information",
    "source": "http://geneontology.org/"
}


@router.get("/bioentity/gene/{id}")
async def bioentity_gene_id(id: str, ):
    """Get GO annotations for a gene"""
    try:
        url = f"{api_info['base_url']}/bioentity/gene/{id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "Gene Ontology", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/ontology/term/{id}")
async def ontology_term_id(id: str, ):
    """Get details for a GO term"""
    try:
        url = f"{api_info['base_url']}/ontology/term/{id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "Gene Ontology", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/search/entity/autocomplete/{term}")
async def search_entity_autocomplete_term(term: str, ):
    """Autocomplete search for entities"""
    try:
        url = f"{api_info['base_url']}/search/entity/autocomplete/{term}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "Gene Ontology", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all endpoints for this API"""
    return {
        "api": "Gene Ontology",
        "base_url": "http://api.geneontology.org/api",
        "category": "annotation",
        "endpoints": [{'path': '/bioentity/gene/{id}', 'method': 'GET', 'description': 'Get GO annotations for a gene'}, {'path': '/ontology/term/{id}', 'method': 'GET', 'description': 'Get details for a GO term'}, {'path': '/search/entity/autocomplete/{term}', 'method': 'GET', 'description': 'Autocomplete search for entities'}]
    }
