# Search APIs - Protein and sequence search tools
from .ensembl_search_router import router as ensembl_search_router
from .ensembl_sequence_router import router as ensembl_sequence_router
from .ensembl_evolution_router import router as ensembl_evolution_router

# uniprot_router will be auto-generated by agent on next run

__all__ = ['ensembl_search_router', 'ensembl_sequence_router', 'ensembl_evolution_router']
