# Auto-generated router for Ensembl Search API
# Generated by autonomous agent at 2026-04-12T03:22:31.119757
# Source: Ensembl REST API
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Dict, Any, List
import requests
import logging

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/ensembl_search", tags=["Ensembl Search API"])

# API Configuration
api_info = {
    "name": "Ensembl Search API",
    "base_url": "https://rest.ensembl.org",
    "prefix": "/ensembl_search",
    "category": "search",
    "description": "Ensembl search endpoints",
    "source": "Ensembl REST API"
}


@router.get("/lookup/id/{id}")
async def lookup_id_id(id: str):
    """Lookup symbol information"""
    try:
        url = f"{api_info['base_url']}/lookup/id/{id}"
        response = requests.get(url, timeout=30)
        response.raise_for_status()
        return {
            "status": "success",
            "api_name": "Ensembl Search API",
            "data": response.json()
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"lookup_id_id failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all available endpoints for this API"""
    return {
        "api_name": "Ensembl Search API",
        "base_url": "https://rest.ensembl.org",
        "category": "search",
        "description": "Ensembl search endpoints",
        "endpoints": [
            {"path": "/lookup/id/{id}", "method": "GET", "description": "Lookup symbol information"}
        ]
    }
