"""
UniProt - Auto-generated Router
====================================
Generated by: Autonomous API Discovery Agent
Generated at: 2026-04-16T02:56:44.359794
Source: https://www.uniprot.org/
Category: protein-data
Description: Central hub for protein sequence and functional information

Endpoints:
  - POST /search: Search for proteins by sequence or accession
  - GET /proteins/{accession}: Get a protein by accession
  - GET /features: Get protein features
  - GET /variation: Get protein variation data

Usage:
    from apis.UniProt import uniprot_router
    app.include_router(uniprot_router)
"""
from fastapi import APIRouter, HTTPException
from typing import Dict, Any, Optional
import requests
import logging

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/uniprot", tags=["UniProt"])

api_info = {
    "name": "UniProt",
    "base_url": "https://rest.uniprot.org/uniprotkb",
    "prefix": "/uniprot",
    "category": "protein-data",
    "description": "Central hub for protein sequence and functional information",
    "source": "https://www.uniprot.org/"
}


@router.post("/search")
async def search_proteins(data: Dict[str, Any] = None):
    """
    Search for proteins by sequence or accession
    
    Expected data format:
    {
        "sequence": "MEDI...",  # Optional: amino acid sequence
        "accession": "P12345",  # Optional: UniProt accession
        "query": "BRCA1",       # Optional: text query
        "organism": "human"     # Optional: organism filter
    }
    """
    try:
        if not data:
            raise HTTPException(status_code=400, detail="Search parameters required")
        
        sequence = data.get("sequence", "")
        accession = data.get("accession", "")
        query = data.get("query", "")
        organism = data.get("organism", "")
        
        results = []
        
        # If accession provided, get specific protein
        if accession:
            protein_details = await get_uniprot_protein_details(accession)
            if protein_details:
                results.append(protein_details)
        
        # If sequence provided, use BLAST to find matches
        elif sequence:
            logger.info(f"Searching UniProt for sequence (length: {len(sequence)})")
            
            # Use UniProt BLAST service
            blast_url = "https://www.uniprot.org/blast/run"
            blast_data = {
                "query": f">query\n{sequence}",
                "database": "uniprotkb",
                "format": "json"
            }
            
            response = requests.post(blast_url, data=blast_data, timeout=60)
            
            if response.status_code == 200:
                blast_result = response.json()
                job_id = blast_result.get("jobId")
                
                if job_id:
                    # Poll for BLAST results
                    import time
                    for attempt in range(30):  # Wait up to 2.5 minutes
                        time.sleep(5)
                        status_resp = requests.get(f"https://www.uniprot.org/blast/status/{job_id}", timeout=30)
                        if status_resp.status_code == 200:
                            status_data = status_resp.json()
                            if status_data.get("status") == "COMPLETE":
                                results_resp = requests.get(f"https://www.uniprot.org/blast/results/{job_id}", timeout=30)
                                if results_resp.status_code == 200:
                                    hits = results_resp.json().get("results", [])[:5]  # Top 5 hits
                                    
                                    for hit in hits:
                                        target_accession = hit.get("targetAccession", "")
                                        if target_accession:
                                            protein_info = await get_uniprot_protein_details(target_accession)
                                            if protein_info:
                                                protein_info["blast_score"] = hit.get("score", 0)
                                                protein_info["evalue"] = hit.get("evalue", 0)
                                                protein_info["identity"] = hit.get("identity", 0)
                                                results.append(protein_info)
                                break
        
        # If text query provided, search by keywords
        elif query:
            search_query = query
            if organism:
                search_query += f" AND organism_name:{organism}"
            
            url = f"{api_info['base_url']}/search?query={search_query}&format=json&size=10"
            response = requests.get(url, timeout=30)
            
            if response.status_code == 200:
                data = response.json()
                for entry in data.get("results", [])[:5]:
                    accession = entry.get("primaryAccession", "")
                    if accession:
                        protein_info = await get_uniprot_protein_details(accession)
                        if protein_info:
                            results.append(protein_info)
        
        return {
            "status": "success",
            "api": "UniProt",
            "count": len(results),
            "data": results
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"UniProt search error: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))


async def get_uniprot_protein_details(accession: str) -> dict | None:
    """Get detailed protein information from UniProt REST API"""
    try:
        url = f"https://rest.uniprot.org/uniprotkb/{accession}.json"
        response = requests.get(url, timeout=30)
        
        if response.status_code == 200:
            data = response.json()
            
            # Extract key information
            protein_name = "Unknown"
            if "proteinDescription" in data:
                rec_name = data["proteinDescription"].get("recommendedName", {})
                if rec_name and "fullName" in rec_name:
                    protein_name = rec_name["fullName"].get("value", "Unknown")
            
            organism = data.get("organism", {}).get("scientificName", "Unknown")
            
            gene_name = "Unknown"
            if data.get("genes"):
                gene_name = data["genes"][0].get("geneName", {}).get("value", "Unknown")
            
            function = "Unknown"
            comments = data.get("comments", [])
            for comment in comments:
                if comment.get("commentType") == "FUNCTION":
                    texts = comment.get("texts", [])
                    if texts:
                        function = texts[0].get("value", "Unknown")
                        break
            
            # Get sequence
            sequence = ""
            if data.get("sequence"):
                sequence = data["sequence"].get("value", "")
            
            return {
                "accession": accession,
                "proteinName": protein_name,
                "organism": organism,
                "geneName": gene_name,
                "function": function,
                "sequence": sequence,
                "sequenceLength": len(sequence),
                "uniprot_url": f"https://www.uniprot.org/uniprotkb/{accession}/entry"
            }
    except Exception as e:
        logger.error(f"Failed to get UniProt details for {accession}: {str(e)}")
    
    return None


@router.get("/proteins/{accession}")
async def get_protein_by_accession(accession: str):
    """Get a protein by accession"""
    try:
        protein_details = await get_uniprot_protein_details(accession)
        
        if protein_details:
            return {"status": "success", "api": "UniProt", "data": protein_details}
        else:
            raise HTTPException(status_code=404, detail=f"Protein {accession} not found")
            
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/features")
async def features():
    """Get protein features"""
    try:
        url = f"{api_info['base_url']}/search?query=*&format=json&size=5&fields=annotation"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "UniProt", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/variation")
async def variation():
    """Get protein variation data"""
    try:
        url = f"{api_info['base_url']}/search?query=*&format=json&size=5&fields=variant"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "UniProt", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all endpoints for this API"""
    return {
        "api": "UniProt",
        "base_url": api_info["base_url"],
        "category": api_info["category"],
        "endpoints": [
            {'path': '/search', 'method': 'POST', 'description': 'Search for proteins by sequence, accession, or query'},
            {'path': '/proteins/{accession}', 'method': 'GET', 'description': 'Get a protein by accession'},
            {'path': '/features', 'method': 'GET', 'description': 'Get protein features'},
            {'path': '/variation', 'method': 'GET', 'description': 'Get protein variation data'}
        ],
        "usage_notes": [
            "Use POST /search with 'sequence' field to find proteins matching your sequence",
            "Use POST /search with 'accession' field to get specific protein details",
            "Use POST /search with 'query' field for text-based searches",
            "Results include protein name, organism, gene, function, and sequence"
        ]
    }