"""
NCBI BLAST - Auto-generated Router
====================================
Generated by: Autonomous API Discovery Agent
Generated at: 2026-04-16T02:52:53.292240
Source: https://blast.ncbi.nlm.nih.gov/
Category: search
Description: Basic Local Alignment Search Tool for sequence similarity

Endpoints:
  - POST /Blast.cgi: Submit BLAST search (CMD=Put)
  - GET /Blast.cgi: Check BLAST status (CMD=Get)
  - GET /Blast.cgi: Get BLAST results (JSON format)

Usage:
    from apis.BLAST import blast_router
    app.include_router(blast_router)
"""
from fastapi import APIRouter, HTTPException
from typing import Dict, Any
import requests
import logging

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/blast", tags=["NCBI BLAST"])

api_info = {
    "name": "NCBI BLAST",
    "base_url": "https://blast.ncbi.nlm.nih.gov",
    "prefix": "/blast",
    "category": "search",
    "description": "Basic Local Alignment Search Tool for sequence similarity",
    "source": "https://blast.ncbi.nlm.nih.gov/"
}


@router.post("/Blast.cgi")
async def Blast_cgi(data: Dict[str, Any] = None):
    """Submit BLAST search (CMD=Put)"""
    try:
        url = f"{api_info['base_url']}/Blast.cgi"
        r = requests.post(url, json=data or {}, timeout=60)
        r.raise_for_status()
        return {"status": "success", "api": "NCBI BLAST", "data": r.json() if r.text else {"ok": True}}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/Blast.cgi")
async def Blast_cgi():
    """Check BLAST status (CMD=Get)"""
    try:
        url = f"{api_info['base_url']}/Blast.cgi"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "NCBI BLAST", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/Blast.cgi")
async def Blast_cgi():
    """Get BLAST results (JSON format)"""
    try:
        url = f"{api_info['base_url']}/Blast.cgi"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "NCBI BLAST", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all endpoints for this API"""
    return {
        "api": "NCBI BLAST",
        "base_url": "https://blast.ncbi.nlm.nih.gov",
        "category": "search",
        "endpoints": [{'path': '/Blast.cgi', 'method': 'POST', 'description': 'Submit BLAST search (CMD=Put)'}, {'path': '/Blast.cgi', 'method': 'GET', 'description': 'Check BLAST status (CMD=Get)'}, {'path': '/Blast.cgi', 'method': 'GET', 'description': 'Get BLAST results (JSON format)'}]
    }

