"""
InterPro - Auto-generated Router
====================================
Generated by: Autonomous API Discovery Agent
Generated at: 2026-04-16T02:52:50.249898
Source: https://www.ebi.ac.uk/interpro/
Category: annotation
Description: Protein family, domain and functional site annotation

Endpoints:
  - GET /api/entry: Search InterPro entries
  - GET /api/entry/InterPro/{id}: Get entry details
  - GET /api/protein/UniProt/{accession}: Get protein annotations
  - POST /api/sequence: Analyze sequence for domains

Usage:
    from apis.InterPro import interpro_router
    app.include_router(interpro_router)
"""
from fastapi import APIRouter, HTTPException
from typing import Dict, Any
import requests
import logging

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/interpro", tags=["InterPro"])

api_info = {
    "name": "InterPro",
    "base_url": "https://www.ebi.ac.uk/interpro",
    "prefix": "/interpro",
    "category": "annotation",
    "description": "Protein family, domain and functional site annotation",
    "source": "https://www.ebi.ac.uk/interpro/"
}


@router.get("/api/entry")
async def api_entry():
    """Search InterPro entries"""
    try:
        url = f"{api_info['base_url']}/api/entry"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "InterPro", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/api/entry/InterPro/{id}")
async def api_entry_InterPro_id(id: str, ):
    """Get entry details"""
    try:
        url = f"{api_info['base_url']}/api/entry/InterPro/{id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "InterPro", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/api/protein/UniProt/{accession}")
async def api_protein_UniProt_accession(accession: str, ):
    """Get protein annotations"""
    try:
        url = f"{api_info['base_url']}/api/protein/UniProt/{accession}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "InterPro", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/api/sequence")
async def api_sequence(data: Dict[str, Any] = None):
    """Analyze sequence for domains"""
    try:
        url = f"{api_info['base_url']}/api/sequence"
        r = requests.post(url, json=data or {}, timeout=60)
        r.raise_for_status()
        return {"status": "success", "api": "InterPro", "data": r.json() if r.text else {"ok": True}}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all endpoints for this API"""
    return {
        "api": "InterPro",
        "base_url": "https://www.ebi.ac.uk/interpro",
        "category": "annotation",
        "endpoints": [{'path': '/api/entry', 'method': 'GET', 'description': 'Search InterPro entries'}, {'path': '/api/entry/InterPro/{id}', 'method': 'GET', 'description': 'Get entry details'}, {'path': '/api/protein/UniProt/{accession}', 'method': 'GET', 'description': 'Get protein annotations'}, {'path': '/api/sequence', 'method': 'POST', 'description': 'Analyze sequence for domains'}]
    }
