# Auto-generated router for Jalview
# Generated by autonomous agent at 2026-04-12T03:53:11.854104
# Source: EBI Tools
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Dict, Any, List
import requests
import logging

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/jalview", tags=["Jalview"])

# API Configuration
api_info = {
    "name": "Jalview",
    "base_url": "https://www.ebi.ac.uk/Tools/services/rest",
    "prefix": "/jalview",
    "category": "alignment",
    "description": "Sequence alignment visualization",
    "source": "EBI Tools"
}


@router.get("/services")
async def services():
    """List available services"""
    try:
        url = f"{api_info['base_url']}/services"
        response = requests.get(url, timeout=30)
        response.raise_for_status()
        return {
            "status": "success",
            "api_name": "Jalview",
            "data": response.json()
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"services failed: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all available endpoints for this API"""
    return {
        "api_name": "Jalview",
        "base_url": "https://www.ebi.ac.uk/Tools/services/rest",
        "category": "alignment",
        "description": "Sequence alignment visualization",
        "endpoints": [
            {"path": "/services", "method": "GET", "description": "List available services"}
        ]
    }
