// Auto-generated API client for Jalview
// Generated by autonomous agent at 2026-04-12T03:17:23.171879
// Source: EBI Tools

const API_CONFIG = {
  BACKEND_URL: import.meta.env.VITE_BACKEND_URL || 'http://localhost:8000'
};

export class JalviewClient {
  static readonly API_NAME = "Jalview";
  static readonly BASE_URL = "https://www.ebi.ac.uk/Tools/services/rest";
  static readonly PREFIX = "/jalview";


  static async services(params?: { [key: string]: string }): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/jalview/services`;
    const queryString = params ? '?' + new URLSearchParams(params).toString() : '';
    const response = await fetch(url + queryString);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return response.json();
  }

  static async discover(): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/jalview/discover`;
    const response = await fetch(url);
    if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);
    return response.json();
  }
}
