// Auto-generated API client for EBI Proteins API
// Generated by autonomous agent at 2026-04-11T06:38:29.659575

const API_CONFIG = {
  BACKEND_URL: import.meta.env.VITE_BACKEND_URL || 'http://localhost:8000'
};

export class EBIProteinsAPIClient {
  static readonly API_NAME = "EBI Proteins API";
  static readonly BASE_URL = "https://www.ebi.ac.uk";
  static readonly PREFIX = "/proteogenomics";


  static async proteins(params?: { [key: string]: string }): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/proteogenomics/proteins`;
    const response = await fetch(url + (params ? '?' + new URLSearchParams(params).toString() : ''));
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return response.json();
  }

  static async coordinates(params?: { [key: string]: string }): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/proteogenomics/coordinates`;
    const response = await fetch(url + (params ? '?' + new URLSearchParams(params).toString() : ''));
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return response.json();
  }

  static async discover(): Promise<any> {
    const url = `${API_CONFIG.BACKEND_URL}/proteogenomics/discover`;
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    return response.json();
  }
}
