"""
MUSCLE - Auto-generated Router
====================================
Generated by: Autonomous API Discovery Agent
Generated at: 2026-04-16T02:53:17.756997
Source: https://www.ebi.ac.uk/Tools/msa/muscle/
Category: alignment
Description: Multiple sequence alignment by MUSCLE

Endpoints:
  - POST /job: Submit MUSCLE alignment
  - GET /status/{job_id}: Check status
  - GET /result/{job_id}: Get result

Usage:
    from apis.Muscle import muscle_router
    app.include_router(muscle_router)
"""
from fastapi import APIRouter, HTTPException
from typing import Dict, Any
import requests
import logging

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/muscle", tags=["MUSCLE"])

api_info = {
    "name": "MUSCLE",
    "base_url": "https://www.ebi.ac.uk/Tools/services/rest/muscle",
    "prefix": "/muscle",
    "category": "alignment",
    "description": "Multiple sequence alignment by MUSCLE",
    "source": "https://www.ebi.ac.uk/Tools/msa/muscle/"
}


@router.post("/job")
async def job(data: Dict[str, Any] = None):
    """Submit MUSCLE alignment"""
    try:
        url = f"{api_info['base_url']}/job"
        r = requests.post(url, json=data or {}, timeout=60)
        r.raise_for_status()
        return {"status": "success", "api": "MUSCLE", "data": r.json() if r.text else {"ok": True}}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/status/{job_id}")
async def status_job_id(job_id: str, ):
    """Check status"""
    try:
        url = f"{api_info['base_url']}/status/{job_id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "MUSCLE", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/result/{job_id}")
async def result_job_id(job_id: str, ):
    """Get result"""
    try:
        url = f"{api_info['base_url']}/result/{job_id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "MUSCLE", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all endpoints for this API"""
    return {
        "api": "MUSCLE",
        "base_url": "https://www.ebi.ac.uk/Tools/services/rest/muscle",
        "category": "alignment",
        "endpoints": [{'path': '/job', 'method': 'POST', 'description': 'Submit MUSCLE alignment'}, {'path': '/status/{job_id}', 'method': 'GET', 'description': 'Check status'}, {'path': '/result/{job_id}', 'method': 'GET', 'description': 'Get result'}]
    }
