"""
NCBI E-utilities - Auto-generated Router
====================================
Generated by: Autonomous API Discovery Agent
Generated at: 2026-04-16T02:56:52.878598
Source: https://www.ncbi.nlm.nih.gov/books/NBK25497/
Category: search
Description: Entrez Programming Utilities for searching and retrieving NCBI data

Endpoints:
  - GET /esearch.fcgi: Search an Entrez database
  - GET /efetch.fcgi: Fetch records from an Entrez database
  - GET /esummary.fcgi: Get document summaries from a list of UIDs

Usage:
    from apis.NCBI import ncbi_router
    app.include_router(ncbi_router)
"""
from fastapi import APIRouter, HTTPException
from typing import Dict, Any
import requests
import logging

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/ncbi", tags=["NCBI E-utilities"])

api_info = {
    "name": "NCBI E-utilities",
    "base_url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils",
    "prefix": "/ncbi",
    "category": "search",
    "description": "Entrez Programming Utilities for searching and retrieving NCBI data",
    "source": "https://www.ncbi.nlm.nih.gov/books/NBK25497/"
}


@router.get("/esearch.fcgi")
async def esearch_fcgi():
    """Search an Entrez database"""
    try:
        url = f"{api_info['base_url']}/esearch.fcgi"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "NCBI E-utilities", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/efetch.fcgi")
async def efetch_fcgi():
    """Fetch records from an Entrez database"""
    try:
        url = f"{api_info['base_url']}/efetch.fcgi"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "NCBI E-utilities", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/esummary.fcgi")
async def esummary_fcgi():
    """Get document summaries from a list of UIDs"""
    try:
        url = f"{api_info['base_url']}/esummary.fcgi"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "NCBI E-utilities", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all endpoints for this API"""
    return {
        "api": "NCBI E-utilities",
        "base_url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils",
        "category": "search",
        "endpoints": [{'path': '/esearch.fcgi', 'method': 'GET', 'description': 'Search an Entrez database'}, {'path': '/efetch.fcgi', 'method': 'GET', 'description': 'Fetch records from an Entrez database'}, {'path': '/esummary.fcgi', 'method': 'GET', 'description': 'Get document summaries from a list of UIDs'}]
    }
