"""
PDBe - Auto-generated Router
====================================
Generated by: Autonomous API Discovery Agent
Generated at: 2026-04-16T02:53:01.943113
Source: https://www.ebi.ac.uk/pdbe/
Category: structure
Description: Protein Data Bank in Europe - 3D structures

Endpoints:
  - GET /pdbe/molecule/{pdb_id}: Get PDB entry
  - GET /pdbe/entry/pdb/{pdb_id}: Get detailed PDB info
  - GET /pdbe/protein/all/{uniprot_id}/summary: Get all structures for protein

Usage:
    from apis.PDBe import pdbe_router
    app.include_router(pdbe_router)
"""
from fastapi import APIRouter, HTTPException
from typing import Dict, Any
import requests
import logging

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/pdbe", tags=["PDBe"])

api_info = {
    "name": "PDBe",
    "base_url": "https://www.ebi.ac.uk/pdbe/api",
    "prefix": "/pdbe",
    "category": "structure",
    "description": "Protein Data Bank in Europe - 3D structures",
    "source": "https://www.ebi.ac.uk/pdbe/"
}


@router.get("/pdbe/molecule/{pdb_id}")
async def pdbe_molecule_pdb_id(pdb_id: str, ):
    """Get PDB entry"""
    try:
        url = f"{api_info['base_url']}/pdbe/molecule/{pdb_id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "PDBe", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/pdbe/entry/pdb/{pdb_id}")
async def pdbe_entry_pdb_pdb_id(pdb_id: str, ):
    """Get detailed PDB info"""
    try:
        url = f"{api_info['base_url']}/pdbe/entry/pdb/{pdb_id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "PDBe", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/pdbe/protein/all/{uniprot_id}/summary")
async def pdbe_protein_all_uniprot_id_summary(uniprot_id: str, ):
    """Get all structures for protein"""
    try:
        url = f"{api_info['base_url']}/pdbe/protein/all/{uniprot_id}/summary"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "PDBe", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all endpoints for this API"""
    return {
        "api": "PDBe",
        "base_url": "https://www.ebi.ac.uk/pdbe/api",
        "category": "structure",
        "endpoints": [{'path': '/pdbe/molecule/{pdb_id}', 'method': 'GET', 'description': 'Get PDB entry'}, {'path': '/pdbe/entry/pdb/{pdb_id}', 'method': 'GET', 'description': 'Get detailed PDB info'}, {'path': '/pdbe/protein/all/{uniprot_id}/summary', 'method': 'GET', 'description': 'Get all structures for protein'}]
    }
