"""
HMMER - Auto-generated Router
====================================
Generated by: Autonomous API Discovery Agent
Generated at: 2026-04-16T02:52:56.214712
Source: https://www.ebi.ac.uk/Tools/hmmer/
Category: search
Description: Protein sequence homology search using profile HMMs

Endpoints:
  - POST /job: Submit HMMER search
  - GET /status/{job_id}: Check search status
  - GET /result/{job_id}: Get search results

Usage:
    from apis.HMMER import hmmer_router
    app.include_router(hmmer_router)
"""
from fastapi import APIRouter, HTTPException
from typing import Dict, Any
import requests
import logging

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/hmmer", tags=["HMMER"])

api_info = {
    "name": "HMMER",
    "base_url": "https://www.ebi.ac.uk/Tools/services/rest/hmmer",
    "prefix": "/hmmer",
    "category": "search",
    "description": "Protein sequence homology search using profile HMMs",
    "source": "https://www.ebi.ac.uk/Tools/hmmer/"
}


@router.post("/job")
async def job(data: Dict[str, Any] = None):
    """Submit HMMER search"""
    try:
        url = f"{api_info['base_url']}/job"
        r = requests.post(url, json=data or {}, timeout=60)
        r.raise_for_status()
        return {"status": "success", "api": "HMMER", "data": r.json() if r.text else {"ok": True}}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/status/{job_id}")
async def status_job_id(job_id: str, ):
    """Check search status"""
    try:
        url = f"{api_info['base_url']}/status/{job_id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "HMMER", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/result/{job_id}")
async def result_job_id(job_id: str, ):
    """Get search results"""
    try:
        url = f"{api_info['base_url']}/result/{job_id}"
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        return {"status": "success", "api": "HMMER", "data": r.json()}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/discover")
async def discover_endpoints():
    """List all endpoints for this API"""
    return {
        "api": "HMMER",
        "base_url": "https://www.ebi.ac.uk/Tools/services/rest/hmmer",
        "category": "search",
        "endpoints": [{'path': '/job', 'method': 'POST', 'description': 'Submit HMMER search'}, {'path': '/status/{job_id}', 'method': 'GET', 'description': 'Check search status'}, {'path': '/result/{job_id}', 'method': 'GET', 'description': 'Get search results'}]
    }
