# Genomics APIs - Genomic analysis and coordinate mapping
from .bio_router import router as bio_router
from .ensembl_genomics_router import router as ensembl_genomics_router
from .ensembl_info_router import router as ensembl_info_router
# proteogenomics_router will be auto-generated by agent on next run

__all__ = ['bio_router', 'ensembl_genomics_router', 'ensembl_info_router']
